version: "3.9"

services:

  auth-service:
    image: samarth02198/auth-service:latest
    build:
      context:  ./auth-service
      dockerfile: DockerFile
    env_file:
      - ./auth-service/.env
    expose:
      - "5000"
    networks:
      - backend-project
    restart: unless-stopped

  profile-service:
    image: samarth02198/profile-service:latest
    build:
      context: ./profile-service
      dockerfile : DockerFile
    env_file:
      - ./profile-service/.env
    expose:
      - "6000"
    networks:
      - backend-project
    restart: unless-stopped

  request-service:
    image: samarth02198/request-service:latest
    build: 
      context : ./request-service
      dockerfile: DockerFile
    env_file:
      - ./request-service/.env
    expose:
      - "7000"
    networks:
      - backend-project
    restart: unless-stopped

  chat-service:
    image: samarth02198/chat-service:latest
    build:
      context :  ./chat-service
      dockerfile : DockerFile
    env_file:
      - ./chat-service/.env
    expose:
      - "8000"
    networks:
      - backend-project
    restart: unless-stopped


networks:
  backend-project:
    driver: bridge
